[package]
name = "merkleized-metadata"
version = "0.1.1"
edition = "2021"
authors = ["Bastian Köcher <git@kchr.de>"]
documentation = "https://docs.rs/merkleized-metadata"
repository = "https://github.com/bkchr/merkleized-metadata"
keywords = ["FRAME", "metadata", "polkadot"]
license = "MIT OR Apache-2.0"
description = """
FRAME metadata merkleization
"""
readme = "./README.md"

[dependencies]
array-bytes = { version = "6.2.2", default-features = false }
blake3 = { version = "1.5.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6.9", features = [ "derive" ], default-features = false }
frame-metadata = { git = "https://github.com/paritytech/frame-metadata", branch = "lexnv/extensions-v16",  features = [ "current" ], default-features = false }
scale-decode = { version = "0.13.0", default-features = false }
scale-info = { version = "2.10.0", default-features = false }

[dev-dependencies]
frame-metadata = { git = "https://github.com/paritytech/frame-metadata", branch = "lexnv/extensions-v16",  features = [ "current", "decode" ], default-features = false }
